LowRSSIAPSteerEdge_RE=34
CUOverloadTh_2G=80
CUOverloadTh_5G_L=70
CUOverloadTh_5G_H=70
PHYBasedSelection=0
MCSRateXingThreshold_DG=6000
MCSRateXingThreshold_UG=50000
RSSISteeringEdge_DG=20
RSSISteeringEdge_UG=20
