#!/bin/sh /etc/rc.common

START=52
USE_PROCD=1

start_service() {
 
    procd_open_instance "led_boss"
    procd_set_param command /usr/bin/zyxel_led_translator
    procd_set_param respawn
    procd_set_param stdout 1
    procd_set_param stderr 1
    procd_close_instance

    
    procd_open_instance "button_boss"
    procd_set_param command /usr/bin/zyxel_button_handler
    procd_set_param respawn
    procd_set_param stdout 1
    procd_set_param stderr 1
    procd_close_instance
}
