#!/bin/sh /etc/rc.common
# Written by Majad Qureshi as part of XX-3310 Port

START=90
STOP=10

ZYXEL_ROOT="/tmp/zyxel_root"

start() {
    echo "=== [1/4] Tuning Kernel & Freeing RAM ===" > /dev/console
    sync; echo 3 > /proc/sys/vm/drop_caches
    
    sysctl -w net.unix.max_dgram_qlen=64 2>/dev/null
    echo 16384 > /proc/net/skbmgr_4k_limit 2>/dev/null
    echo 20000 > /proc/net/skbmgr_limit 2>/dev/null
    echo 40000 > /proc/net/skbmgr_driver_max_skb 2>/dev/null
    echo 4096 2048 > /proc/net/skbmgr_hot_list_len 2>/dev/null

    echo "=== [2/4] Building ... ===" > /dev/console
    umount -l $ZYXEL_ROOT/proc $ZYXEL_ROOT/sys $ZYXEL_ROOT/dev $ZYXEL_ROOT/tmp $ZYXEL_ROOT/bin $ZYXEL_ROOT/sbin $ZYXEL_ROOT/usr $ZYXEL_ROOT/lib $ZYXEL_ROOT/userfs $ZYXEL_ROOT/etc $ZYXEL_ROOT/data 2>/dev/null
    rm -rf $ZYXEL_ROOT
    
    mkdir -p $ZYXEL_ROOT
    #mount -t tmpfs tmpfs $ZYXEL_ROOT
	mount -o bind /tmp $ZYXEL_ROOT/tmp
    mkdir -p $ZYXEL_ROOT/bin $ZYXEL_ROOT/sbin $ZYXEL_ROOT/usr $ZYXEL_ROOT/lib $ZYXEL_ROOT/lib/modules $ZYXEL_ROOT/userfs $ZYXEL_ROOT/proc $ZYXEL_ROOT/sys $ZYXEL_ROOT/dev $ZYXEL_ROOT/tmp $ZYXEL_ROOT/etc $ZYXEL_ROOT/var $ZYXEL_ROOT/data

    mount -o bind /os/bin $ZYXEL_ROOT/bin
    mount -o bind /os/sbin $ZYXEL_ROOT/sbin
    mount -o bind /os/usr $ZYXEL_ROOT/usr
    mount -o bind /os/lib $ZYXEL_ROOT/lib
    mount -o bind /os/userfs $ZYXEL_ROOT/userfs
	#uncomment this line to force manual data input
    #mount -o bind /os/data $ZYXEL_ROOT/data
	mount -o bind /data $ZYXEL_ROOT/data
	mount -o bind /lib/modules $ZYXEL_ROOT/lib/modules


    mkdir -p /tmp/z_etc_upper /tmp/z_etc_work
    mount -t overlay overlay -o lowerdir=/os/etc,upperdir=/tmp/z_etc_upper,workdir=/tmp/z_etc_work $ZYXEL_ROOT/etc

    mount -o bind /proc $ZYXEL_ROOT/proc
    mount -o bind /sys $ZYXEL_ROOT/sys
    mount -o bind /dev $ZYXEL_ROOT/dev
    mount -t tmpfs tmpfs $ZYXEL_ROOT/tmp

    echo "=== [3/4] Injecting Identity & Wi-Fi Portal ===" > /dev/console
    mkdir -p $ZYXEL_ROOT/etc/Wireless/RT2860AP/
    mkdir -p $ZYXEL_ROOT/etc/Wireless/RT2860AP_AC/
    
    dd if=/dev/mtd13 of=$ZYXEL_ROOT/etc/Wireless/RT2860AP/RT30xxEEPROM.bin bs=1 skip=172032 count=4096 2>/dev/null
    cp $ZYXEL_ROOT/etc/Wireless/RT2860AP/RT30xxEEPROM.bin $ZYXEL_ROOT/etc/Wireless/RT2860AP_AC/RT30xxEEPROM.bin 2>/dev/null

    cp /data/RT2860AP_bak.dat $ZYXEL_ROOT/etc/Wireless/RT2860AP/RT2860AP.dat 2>/dev/null
    cp /data/RT2860AP_AC_bak.dat $ZYXEL_ROOT/etc/Wireless/RT2860AP_AC/RT2860AP.dat 2>/dev/null

    #echo "MacAddress=7C:77:16:EC:E8:40" >> $ZYXEL_ROOT/etc/Wireless/RT2860AP/RT2860AP.dat
    echo "E2pPhiBinPath=/etc/Wireless/RT2860AP/RT30xxEEPROM.bin" >> $ZYXEL_ROOT/etc/Wireless/RT2860AP/RT2860AP.dat
    #echo "MacAddress=7C:77:16:EC:E8:41" >> $ZYXEL_ROOT/etc/Wireless/RT2860AP_AC/RT2860AP.dat
    echo "E2pPhiBinPath=/etc/Wireless/RT2860AP_AC/RT30xxEEPROM.bin" >> $ZYXEL_ROOT/etc/Wireless/RT2860AP_AC/RT2860AP.dat

    #rm -rf /etc/Wireless 2>/dev/null
    #mkdir -p /etc/Wireless
    #mount -o bind $ZYXEL_ROOT/etc/Wireless /etc/Wireless
	rm -rf /etc/Wireless 2>/dev/null
	ln -s $ZYXEL_ROOT/etc/Wireless /etc/Wireless
	
    echo "=== [4/4] Launching Matrix Ecosystem ===" > /dev/console
    
    insmod /lib/modules/3.18.21/tcledctrl.ko 2>/dev/null
    insmod /lib/modules/3.18.21/tccicmd.ko 2>/dev/null

    # Fix : Provide a dummy br0 
    brctl addbr br0 2>/dev/null
    ifconfig br0 up 2>/dev/null

    chroot $ZYXEL_ROOT /bin/sh -c "export PATH=/home/bin:/home/scripts:/opt/bin:/bin:/sbin:/usr/bin:/usr/sbin:/userfs/bin; export LD_LIBRARY_PATH=/lib/public:/lib/private:/lib/gpl:/usr/lib:/lib:/lib64/gpl:/lib64; /etc/init.d/rcS start"

    echo -n "Matrix Initialization: [" > /dev/console
    for i in $(seq 1 20); do
        echo -n " > " > /dev/console
        sleep 1
    done
    echo "] 100% Complete!" > /dev/console
    ifconfig br0 down 2>/dev/null

    # FIx Destroy the dummy bridge
    brctl delbr br0 2>/dev/null
	touch /overlay/.reset
    echo -n "Setup Network ... [" > /dev/console
    for i in $(seq 1 5); do
        echo -n " > " > /dev/console
        sleep 1
    done
	/etc/init.d/network stop
	/etc/init.d/zyxel_wifi stop
    echo " 100% ]" > /dev/console

    echo "=== Mounting ===" > /dev/console
    mount -o bind /dev /tmp/zyxel_root/dev 2>/dev/null
    mount -o bind /proc /tmp/zyxel_root/proc 2>/dev/null
    mount -o bind /sys /tmp/zyxel_root/sys 2>/dev/null
    mkdir -p /tmp/hosts/dhcp
  
	echo "V15" > /tmp/sysinfo/model ; mkdir /tmp/sysinfo ; echo "EX-3310-T0" > /tmp/sysinfo/board_name
    SSID_2G=$(uci -q get wireless.@wifi-iface[0].ssid)
    KEY_2G=$(uci -q get wireless.@wifi-iface[0].key)
    SSID_5G=$(uci -q get wireless.@wifi-iface[1].ssid)
    KEY_5G=$(uci -q get wireless.@wifi-iface[1].key)

	for i in $(seq 1 1); do
		echo "17 38 2 0 1" > /proc/tc3162/led_def
		sleep 1
		echo "17 38 2 0 0" > /proc/tc3162/led_def
	done
      mkdir -p /tmp/sysinfo ; echo "Zyxel-Matrix V-15" >> /tmp/sysinfo/model
	#maping wifi  2 and 5 ghz on two cpus
	echo 2 > /proc/irq/21/smp_affinity   
	echo 4 > /proc/irq/20/smp_affinity   
	#binding wifi
	echo 0 0 0 0 > /proc/tc3162/sw_rps 2>/dev/null
	echo 0 0 1 0 > /proc/tc3162/sw_rps_2g 2>/dev/null
	#tuning
	echo 1 > /proc/tc3162/igmp_hwnat 2>/dev/null
	echo 1 1 1 0 > /proc/tc3162/sw_rps 2>/dev/null
	echo 1 1 1 0 > /proc/tc3162/sw_rps_2g 2>/dev/null

        echo -n " > " > /dev/console
                for i in $(seq 1 5); do
                        echo -n " > " > /dev/console
                        sleep 1
        done
        echo -n " > > > " > /dev/console
		echo -n " > > System Ready! " 
        LAN_NET=$(/os/usr/sbin/ip -o -f inet addr show br-lan | awk '{print $4}')
        echo 1 > /proc/sys/net/ipv4/ip_forward 2>/dev/null
		echo 1 > /proc/tc3162/hwnat_off 2>/dev/null
		echo 1 > /proc/tc3162/sw_rps 2>/dev/null
		echo 1 > /proc/tc3162/sw_rps_2g 2>/dev/null
		echo 0 > /proc/tc3162/igmp_hwnat 2>/dev/null
		echo 1 > /proc/tc3162/rps_enable 2>/dev/null
       if [ -n "$LAN_NET" ]; then
                #chroot /tmp/zyxel_root /usr/sbin/iptables -t nat -A POSTROUTING -s $LAN_NET -o nas10 -j MASQUERADE
				/etc/init.d/network stop				
       fi
		echo "80 8 1 0 0" > /proc/tc3162/led_def ;		echo "82 6 1 0 1" > /proc/tc3162/led_def
        chroot /tmp/zyxel_root /usr/sbin/iptables -t nat -A POSTROUTING -o nas10 -j MASQUERADE
        chroot /tmp/zyxel_root /usr/sbin/iptables -P INPUT ACCEPT
        chroot /tmp/zyxel_root /usr/sbin/iptables -I INPUT -p udp --dport 53 -j ACCEPT
        chroot /tmp/zyxel_root /usr/sbin/iptables -t mangle -A FORWARD -p tcp --tcp-flags SYN,RST SYN -j TCPMSS --clamp-mss-to-pmtu
        chroot /tmp/zyxel_root /usr/sbin/iptables -P FORWARD ACCEPT
        echo "nameserver 8.8.8.8" > /etc/resolv.conf
		/usr/sbin/dnsmasq -u root -S 8.8.8.8 -S 8.8.4.4
		echo 0 > /proc/tc3162/led_pwr_red ; sleep 10 ;		echo 1 > /proc/tc3162/led_pwr_red
			#uncomment to remove HW driver,  if wifi speed is slow
			#rmmod hw_nat.ko
		echo -n " > " > /dev/console
                for i in $(seq 1 3); do
                        echo -n " > " > /dev/console
                        sleep 1
        done
		echo " 100% ] ...  Restarting Network" > /dev/console
		/etc/init.d/network start	
		/etc/init.d/zyxel_wifi start
		for i in $(seq 1 1); do
		echo "34 4 2 0 1" > /proc/tc3162/led_def 
		sleep 1
		echo "34 4 2 0 0" > /proc/tc3162/led_def 
		done
		for i in $(seq 1 15); do
        echo -n " > " > /dev/console
        sleep 1
		done
		echo " 100%  Ready! - Press any key to login ...]" > /dev/console
}

stop() {
    echo "Stopping Matrix..." > /dev/console
    killall -9 zywifid 2>/dev/null
    killall -9 zcmd 2>/dev/null
    rmmod tccicmd tcledctrl 2>/dev/null
    
    umount -l /etc/Wireless 2>/dev/null
    
    umount -l $ZYXEL_ROOT/etc 2>/dev/null
    rm -rf /tmp/z_etc_upper /tmp/z_etc_work
    
    umount -l $ZYXEL_ROOT/proc $ZYXEL_ROOT/sys $ZYXEL_ROOT/dev $ZYXEL_ROOT/tmp $ZYXEL_ROOT/bin $ZYXEL_ROOT/sbin $ZYXEL_ROOT/usr $ZYXEL_ROOT/lib $ZYXEL_ROOT/userfs $ZYXEL_ROOT/data 2>/dev/null
    umount -l $ZYXEL_ROOT 2>/dev/null
    rm -rf $ZYXEL_ROOT
    echo "Matrix Stopped and RAM Cleared." > /dev/console
}