#!/bin/sh

# Copyright (C) ZyXEL Communications, Corp. All Rights Reserved.

# $1: device number
# $2: VID
# $3: PID

#set -x

# Environment Variables
#WWANPATH=/sbin  # set the WWAN directory path #~!@#$%^&*()_+

. $WWANPATH/wwan-lib.sh

wwan_log "[$0] enter"

DEVICE_NUMBER=$1
VID=$2
PID=$3
if [ "$DEVICE_NUMBER" = "" -o "$VID" = "" -o "$PID" = "" ]; then
	wwan_log "[$0] DEVICE_NUMBER=$DEVICE_NUMBER, VID=$VID, PID=$PID; can't find DEVICE_NUMBER or VID or PID"
	exit
fi

DEVICE_ID=$DEVICE_NUMBER:$VID:$PID
DEVICE_DIR=$DATAPATH/$DEVICE_DATA_PRENAME:$DEVICE_ID
if [ ! -e "$DEVICE_DIR" ]; then
	wwan_log "[$0] can't find DEVICE_DIR $DEVICE_DIR, exit"
	exit
fi

DEVICE_STATUS_FILE=$DEVICE_DIR/$DEVICE_STATUS_NAME
DEVICE_INIT_FILE=$DEVICE_DIR/$DEVICE_INIT_NAME
DEVICE_TYPE_FILE=$DEVICE_DIR/$DEVICE_TYPE_NAME
DEVICE_DRIVER_FILE=$DEVICE_DIR/$DEVICE_DRIVER_NAME
DEVICE_DIAL_FILE=$DEVICE_DIR/$DEVICE_DIAL_IF_NAME
DEVICE_CMD_FILE=$DEVICE_DIR/$DEVICE_CMD_IF_NAME
DEVICE_PECULIAR_FILE=$DEVICE_DIR/$DEVICE_PECULIAR_NAME
#DEVICE_MODEL_FILE=$DEVICE_DIR/$DEVICE_MODEL_NAME

DEVICE_INFO_FILE=$DEVICE_DIR/$DEVICE_INFO_NAME

rm -rf $DEVICE_INFO_FILE

DEVICE_STATUS_VALUE=`cat $DEVICE_STATUS_FILE`
echo "$DEVICE_STATUS_NAME:$DEVICE_STATUS_VALUE" >> $DEVICE_INFO_FILE
DEVICE_INIT_VALUE=`cat $DEVICE_INIT_FILE`
echo "$DEVICE_INIT_NAME:$DEVICE_INIT_VALUE" >> $DEVICE_INFO_FILE
DEVICE_TYPE_VALUE=`cat $DEVICE_TYPE_FILE`
echo "$DEVICE_TYPE_NAME:$DEVICE_TYPE_VALUE" >> $DEVICE_INFO_FILE
DEVICE_DRIVER_VALUE=`cat $DEVICE_DRIVER_FILE`
echo "$DEVICE_DRIVER_NAME:$DEVICE_DRIVER_VALUE" >> $DEVICE_INFO_FILE
DEVICE_DIAL_VALUE=`cat $DEVICE_DIAL_FILE`
echo "$DEVICE_DIAL_IF_NAME:$DEVICE_DIAL_VALUE" >> $DEVICE_INFO_FILE
DEVICE_CMD_VALUE=`cat $DEVICE_CMD_FILE`
echo "$DEVICE_CMD_IF_NAME:$DEVICE_CMD_VALUE" >> $DEVICE_INFO_FILE
if [ -f "$DEVICE_PECULIAR_FILE" ]; then
	DEVICE_PECULIAR_VALUE=`cat $DEVICE_PECULIAR_FILE`
	echo "$DEVICE_PECULIAR_NAME:$DEVICE_PECULIAR_VALUE" >> $DEVICE_INFO_FILE
fi
#DEVICE_MODEL_VALUE=`cat $DEVICE_MODEL_FILE`
#echo "$DEVICE_MODEL_NAME:$DEVICE_MODEL_VALUE" >> $DEVICE_INFO_FILE

wwan_log "[$0] update into done, exit"
#exit
