cmd_scripts/basic/docproc := gcc -Wp,-MD,scripts/basic/.docproc.d -Wall -Wstrict-prototypes -O2 -fomit-frame-pointer       -o scripts/basic/docproc scripts/basic/docproc.c  

deps_scripts/basic/docproc := \
  scripts/basic/docproc.c \
  /usr/x86_64-linux-gnu/include/stdc-predef.h \
  /usr/x86_64-linux-gnu/include/stdio.h \
  /usr/x86_64-linux-gnu/include/bits/libc-header-start.h \
  /usr/x86_64-linux-gnu/include/features.h \
  /usr/x86_64-linux-gnu/include/features-time64.h \
  /usr/x86_64-linux-gnu/include/bits/wordsize.h \
  /usr/x86_64-linux-gnu/include/bits/timesize.h \
  /usr/x86_64-linux-gnu/include/sys/cdefs.h \
  /usr/x86_64-linux-gnu/include/bits/long-double.h \
  /usr/x86_64-linux-gnu/include/gnu/stubs.h \
  /usr/x86_64-linux-gnu/include/gnu/stubs-64.h \
  /usr/lib/gcc/x86_64-linux-gnu/11/include/stddef.h \
  /usr/lib/gcc/x86_64-linux-gnu/11/include/stdarg.h \
  /usr/x86_64-linux-gnu/include/bits/types.h \
  /usr/x86_64-linux-gnu/include/bits/typesizes.h \
  /usr/x86_64-linux-gnu/include/bits/time64.h \
  /usr/x86_64-linux-gnu/include/bits/types/__fpos_t.h \
  /usr/x86_64-linux-gnu/include/bits/types/__mbstate_t.h \
  /usr/x86_64-linux-gnu/include/bits/types/__fpos64_t.h \
  /usr/x86_64-linux-gnu/include/bits/types/__FILE.h \
  /usr/x86_64-linux-gnu/include/bits/types/FILE.h \
  /usr/x86_64-linux-gnu/include/bits/types/struct_FILE.h \
  /usr/x86_64-linux-gnu/include/bits/stdio_lim.h \
  /usr/x86_64-linux-gnu/include/bits/floatn.h \
  /usr/x86_64-linux-gnu/include/bits/floatn-common.h \
  /usr/x86_64-linux-gnu/include/bits/stdio.h \
  /usr/x86_64-linux-gnu/include/bits/stdio2.h \
  /usr/x86_64-linux-gnu/include/stdlib.h \
  /usr/x86_64-linux-gnu/include/bits/waitflags.h \
  /usr/x86_64-linux-gnu/include/bits/waitstatus.h \
  /usr/x86_64-linux-gnu/include/sys/types.h \
  /usr/x86_64-linux-gnu/include/bits/types/clock_t.h \
  /usr/x86_64-linux-gnu/include/bits/types/clockid_t.h \
  /usr/x86_64-linux-gnu/include/bits/types/time_t.h \
  /usr/x86_64-linux-gnu/include/bits/types/timer_t.h \
  /usr/x86_64-linux-gnu/include/bits/stdint-intn.h \
  /usr/x86_64-linux-gnu/include/endian.h \
  /usr/x86_64-linux-gnu/include/bits/endian.h \
  /usr/x86_64-linux-gnu/include/bits/endianness.h \
  /usr/x86_64-linux-gnu/include/bits/byteswap.h \
  /usr/x86_64-linux-gnu/include/bits/uintn-identity.h \
  /usr/x86_64-linux-gnu/include/sys/select.h \
  /usr/x86_64-linux-gnu/include/bits/select.h \
  /usr/x86_64-linux-gnu/include/bits/types/sigset_t.h \
  /usr/x86_64-linux-gnu/include/bits/types/__sigset_t.h \
  /usr/x86_64-linux-gnu/include/bits/types/struct_timeval.h \
  /usr/x86_64-linux-gnu/include/bits/types/struct_timespec.h \
  /usr/x86_64-linux-gnu/include/bits/select2.h \
  /usr/x86_64-linux-gnu/include/bits/pthreadtypes.h \
  /usr/x86_64-linux-gnu/include/bits/thread-shared-types.h \
  /usr/x86_64-linux-gnu/include/bits/pthreadtypes-arch.h \
  /usr/x86_64-linux-gnu/include/bits/atomic_wide_counter.h \
  /usr/x86_64-linux-gnu/include/bits/struct_mutex.h \
  /usr/x86_64-linux-gnu/include/bits/struct_rwlock.h \
  /usr/x86_64-linux-gnu/include/alloca.h \
  /usr/x86_64-linux-gnu/include/bits/stdlib-bsearch.h \
  /usr/x86_64-linux-gnu/include/bits/stdlib-float.h \
  /usr/x86_64-linux-gnu/include/bits/stdlib.h \
  /usr/x86_64-linux-gnu/include/string.h \
  /usr/x86_64-linux-gnu/include/bits/types/locale_t.h \
  /usr/x86_64-linux-gnu/include/bits/types/__locale_t.h \
  /usr/x86_64-linux-gnu/include/strings.h \
  /usr/x86_64-linux-gnu/include/bits/strings_fortified.h \
  /usr/x86_64-linux-gnu/include/bits/string_fortified.h \
  /usr/x86_64-linux-gnu/include/ctype.h \
  /usr/x86_64-linux-gnu/include/unistd.h \
  /usr/x86_64-linux-gnu/include/bits/posix_opt.h \
  /usr/x86_64-linux-gnu/include/bits/environments.h \
  /usr/x86_64-linux-gnu/include/bits/confname.h \
  /usr/x86_64-linux-gnu/include/bits/getopt_posix.h \
  /usr/x86_64-linux-gnu/include/bits/getopt_core.h \
  /usr/x86_64-linux-gnu/include/bits/unistd.h \
  /usr/x86_64-linux-gnu/include/bits/unistd_ext.h \
  /usr/lib/gcc/x86_64-linux-gnu/11/include/limits.h \
  /usr/lib/gcc/x86_64-linux-gnu/11/include/syslimits.h \
  /usr/x86_64-linux-gnu/include/limits.h \
  /usr/x86_64-linux-gnu/include/bits/posix1_lim.h \
  /usr/x86_64-linux-gnu/include/bits/local_lim.h \
  /usr/x86_64-linux-gnu/include/linux/limits.h \
  /usr/x86_64-linux-gnu/include/bits/pthread_stack_min-dynamic.h \
  /usr/x86_64-linux-gnu/include/bits/pthread_stack_min.h \
  /usr/x86_64-linux-gnu/include/bits/posix2_lim.h \
  /usr/x86_64-linux-gnu/include/sys/wait.h \
  /usr/x86_64-linux-gnu/include/signal.h \
  /usr/x86_64-linux-gnu/include/bits/signum-generic.h \
  /usr/x86_64-linux-gnu/include/bits/signum-arch.h \
  /usr/x86_64-linux-gnu/include/bits/types/sig_atomic_t.h \
  /usr/x86_64-linux-gnu/include/bits/types/siginfo_t.h \
  /usr/x86_64-linux-gnu/include/bits/types/__sigval_t.h \
  /usr/x86_64-linux-gnu/include/bits/siginfo-arch.h \
  /usr/x86_64-linux-gnu/include/bits/siginfo-consts.h \
  /usr/x86_64-linux-gnu/include/bits/types/sigval_t.h \
  /usr/x86_64-linux-gnu/include/bits/types/sigevent_t.h \
  /usr/x86_64-linux-gnu/include/bits/sigevent-consts.h \
  /usr/x86_64-linux-gnu/include/bits/sigaction.h \
  /usr/x86_64-linux-gnu/include/bits/sigcontext.h \
  /usr/x86_64-linux-gnu/include/bits/types/stack_t.h \
  /usr/x86_64-linux-gnu/include/sys/ucontext.h \
  /usr/x86_64-linux-gnu/include/bits/sigstack.h \
  /usr/x86_64-linux-gnu/include/bits/sigstksz.h \
  /usr/x86_64-linux-gnu/include/bits/ss_flags.h \
  /usr/x86_64-linux-gnu/include/bits/types/struct_sigstack.h \
  /usr/x86_64-linux-gnu/include/bits/sigthread.h \
  /usr/x86_64-linux-gnu/include/bits/signal_ext.h \

scripts/basic/docproc: $(deps_scripts/basic/docproc)

$(deps_scripts/basic/docproc):
